# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/vryndara.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'protos/vryndara.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15protos/vryndara.proto\x12\x08vryndara\"=\n\tAgentInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x02 \x03(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"x\n\x06Signal\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0fsource_agent_id\x18\x02 \x01(\t\x12\x17\n\x0ftarget_agent_id\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\"%\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2\x9a\x01\n\x06Kernel\x12.\n\x08Register\x12\x13.vryndara.AgentInfo\x1a\r.vryndara.Ack\x12*\n\x07Publish\x12\x10.vryndara.Signal\x1a\r.vryndara.Ack\x12\x34\n\tSubscribe\x12\x13.vryndara.AgentInfo\x1a\x10.vryndara.Signal0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.vryndara_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTINFO']._serialized_start=35
  _globals['_AGENTINFO']._serialized_end=96
  _globals['_SIGNAL']._serialized_start=98
  _globals['_SIGNAL']._serialized_end=218
  _globals['_ACK']._serialized_start=220
  _globals['_ACK']._serialized_end=257
  _globals['_KERNEL']._serialized_start=260
  _globals['_KERNEL']._serialized_end=414
# @@protoc_insertion_point(module_scope)
