# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import vryndara_pb2 as protos_dot_vryndara__pb2
from protos import vryndara_pb2 as protos__slash__vryndara__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in protos/vryndara_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KernelStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/vryndara.Kernel/Register',
                request_serializer=protos_dot_vryndara__pb2.AgentInfo.SerializeToString,
                response_deserializer=protos_dot_vryndara__pb2.Ack.FromString,
                _registered_method=True)
        self.Publish = channel.unary_unary(
                '/vryndara.Kernel/Publish',
                request_serializer=protos_dot_vryndara__pb2.Signal.SerializeToString,
                response_deserializer=protos_dot_vryndara__pb2.Ack.FromString,
                _registered_method=True)
        self.Subscribe = channel.unary_stream(
                '/vryndara.Kernel/Subscribe',
                request_serializer=protos_dot_vryndara__pb2.AgentInfo.SerializeToString,
                response_deserializer=protos_dot_vryndara__pb2.Signal.FromString,
                _registered_method=True)


class KernelServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Publish(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Subscribe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KernelServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=protos_dot_vryndara__pb2.AgentInfo.FromString,
                    response_serializer=protos_dot_vryndara__pb2.Ack.SerializeToString,
            ),
            'Publish': grpc.unary_unary_rpc_method_handler(
                    servicer.Publish,
                    request_deserializer=protos_dot_vryndara__pb2.Signal.FromString,
                    response_serializer=protos_dot_vryndara__pb2.Ack.SerializeToString,
            ),
            'Subscribe': grpc.unary_stream_rpc_method_handler(
                    servicer.Subscribe,
                    request_deserializer=protos_dot_vryndara__pb2.AgentInfo.FromString,
                    response_serializer=protos_dot_vryndara__pb2.Signal.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vryndara.Kernel', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vryndara.Kernel', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Kernel(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vryndara.Kernel/Register',
            protos_dot_vryndara__pb2.AgentInfo.SerializeToString,
            protos_dot_vryndara__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Publish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vryndara.Kernel/Publish',
            protos_dot_vryndara__pb2.Signal.SerializeToString,
            protos_dot_vryndara__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Subscribe(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/vryndara.Kernel/Subscribe',
            protos_dot_vryndara__pb2.AgentInfo.SerializeToString,
            protos_dot_vryndara__pb2.Signal.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
