# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vryndara.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vryndara.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0evryndara.proto\x12\x08vryndara\"=\n\tAgentInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\x14\n\x0c\x63\x61pabilities\x18\x02 \x03(\t\x12\x0e\n\x06status\x18\x03 \x01(\t\"x\n\x06Signal\x12\n\n\x02id\x18\x01 \x01(\t\x12\x17\n\x0fsource_agent_id\x18\x02 \x01(\t\x12\x17\n\x0ftarget_agent_id\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\t\x12\x0f\n\x07payload\x18\x05 \x01(\t\x12\x11\n\ttimestamp\x18\x06 \x01(\x03\"%\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"i\n\x0eSpatialRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x11\n\tobject_id\x18\x02 \x01(\t\x12\x0f\n\x07gesture\x18\x03 \x01(\t\x12\t\n\x01x\x18\x04 \x01(\x02\x12\t\n\x01y\x18\x05 \x01(\x02\x12\t\n\x01z\x18\x06 \x01(\x02\"Y\n\x0fHologramCommand\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x15\n\rtarget_object\x18\x02 \x01(\t\x12\t\n\x01x\x18\x03 \x01(\x02\x12\t\n\x01y\x18\x04 \x01(\x02\x12\t\n\x01z\x18\x05 \x01(\x02\"q\n\rNodeHeartbeat\x12\x0f\n\x07node_id\x18\x01 \x01(\t\x12\x11\n\tcpu_usage\x18\x02 \x01(\x02\x12\x11\n\tram_usage\x18\x03 \x01(\x02\x12\x12\n\non_battery\x18\x04 \x01(\x08\x12\x15\n\rbattery_level\x18\x05 \x01(\x05\"J\n\x0cWorkflowStep\x12\x10\n\x08\x61gent_id\x18\x01 \x01(\t\x12\x14\n\x0ctask_payload\x18\x02 \x01(\t\x12\x12\n\nstep_order\x18\x03 \x01(\x05\"M\n\x0fWorkflowRequest\x12\x13\n\x0bworkflow_id\x18\x01 \x01(\t\x12%\n\x05steps\x18\x02 \x03(\x0b\x32\x16.vryndara.WorkflowStep2\xd9\x02\n\x06Kernel\x12.\n\x08Register\x12\x13.vryndara.AgentInfo\x1a\r.vryndara.Ack\x12*\n\x07Publish\x12\x10.vryndara.Signal\x1a\r.vryndara.Ack\x12\x34\n\tSubscribe\x12\x13.vryndara.AgentInfo\x1a\x10.vryndara.Signal0\x01\x12;\n\x0f\x45xecuteWorkflow\x12\x19.vryndara.WorkflowRequest\x1a\r.vryndara.Ack\x12L\n\x11StreamSpatialData\x12\x18.vryndara.SpatialRequest\x1a\x19.vryndara.HologramCommand(\x01\x30\x01\x12\x32\n\x08NodePing\x12\x17.vryndara.NodeHeartbeat\x1a\r.vryndara.Ackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vryndara_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_AGENTINFO']._serialized_start=28
  _globals['_AGENTINFO']._serialized_end=89
  _globals['_SIGNAL']._serialized_start=91
  _globals['_SIGNAL']._serialized_end=211
  _globals['_ACK']._serialized_start=213
  _globals['_ACK']._serialized_end=250
  _globals['_SPATIALREQUEST']._serialized_start=252
  _globals['_SPATIALREQUEST']._serialized_end=357
  _globals['_HOLOGRAMCOMMAND']._serialized_start=359
  _globals['_HOLOGRAMCOMMAND']._serialized_end=448
  _globals['_NODEHEARTBEAT']._serialized_start=450
  _globals['_NODEHEARTBEAT']._serialized_end=563
  _globals['_WORKFLOWSTEP']._serialized_start=565
  _globals['_WORKFLOWSTEP']._serialized_end=639
  _globals['_WORKFLOWREQUEST']._serialized_start=641
  _globals['_WORKFLOWREQUEST']._serialized_end=718
  _globals['_KERNEL']._serialized_start=721
  _globals['_KERNEL']._serialized_end=1066
# @@protoc_insertion_point(module_scope)
